project_id = "wnwhonxoshhmgsbspade"

[functions.investment-chat]
verify_jwt = false

[functions.update-stock-prices]
verify_jwt = false

[functions.generate-ideas]
verify_jwt = false

[functions.angel-one-auth]
verify_jwt = false

[functions.angel-one-portfolio]
verify_jwt = false

[functions.angel-one-ltp]
verify_jwt = false
